// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteProductReader is a Reader for the DeleteProduct structure.
type DeleteProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteProductCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /products/{id}] deleteProduct", response, response.Code())
	}
}

// NewDeleteProductCreated creates a DeleteProductCreated with default headers values
func NewDeleteProductCreated() *DeleteProductCreated {
	return &DeleteProductCreated{}
}

/*
DeleteProductCreated describes a response with status code 201, with default header values.

DeleteProductCreated delete product created
*/
type DeleteProductCreated struct {
}

// IsSuccess returns true when this delete product created response has a 2xx status code
func (o *DeleteProductCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete product created response has a 3xx status code
func (o *DeleteProductCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete product created response has a 4xx status code
func (o *DeleteProductCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete product created response has a 5xx status code
func (o *DeleteProductCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this delete product created response a status code equal to that given
func (o *DeleteProductCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the delete product created response
func (o *DeleteProductCreated) Code() int {
	return 201
}

func (o *DeleteProductCreated) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductCreated", 201)
}

func (o *DeleteProductCreated) String() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductCreated", 201)
}

func (o *DeleteProductCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
