// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetSingleProductReader is a Reader for the GetSingleProduct structure.
type GetSingleProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSingleProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSingleProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /products/{id}] getSingleProduct", response, response.Code())
	}
}

// NewGetSingleProductOK creates a GetSingleProductOK with default headers values
func NewGetSingleProductOK() *GetSingleProductOK {
	return &GetSingleProductOK{}
}

/*
GetSingleProductOK describes a response with status code 200, with default header values.

GetSingleProductOK get single product o k
*/
type GetSingleProductOK struct {
}

// IsSuccess returns true when this get single product o k response has a 2xx status code
func (o *GetSingleProductOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get single product o k response has a 3xx status code
func (o *GetSingleProductOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get single product o k response has a 4xx status code
func (o *GetSingleProductOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get single product o k response has a 5xx status code
func (o *GetSingleProductOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get single product o k response a status code equal to that given
func (o *GetSingleProductOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get single product o k response
func (o *GetSingleProductOK) Code() int {
	return 200
}

func (o *GetSingleProductOK) Error() string {
	return fmt.Sprintf("[GET /products/{id}][%d] getSingleProductOK", 200)
}

func (o *GetSingleProductOK) String() string {
	return fmt.Sprintf("[GET /products/{id}][%d] getSingleProductOK", 200)
}

func (o *GetSingleProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
