// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSingleProductParams creates a new GetSingleProductParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSingleProductParams() *GetSingleProductParams {
	return &GetSingleProductParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSingleProductParamsWithTimeout creates a new GetSingleProductParams object
// with the ability to set a timeout on a request.
func NewGetSingleProductParamsWithTimeout(timeout time.Duration) *GetSingleProductParams {
	return &GetSingleProductParams{
		timeout: timeout,
	}
}

// NewGetSingleProductParamsWithContext creates a new GetSingleProductParams object
// with the ability to set a context for a request.
func NewGetSingleProductParamsWithContext(ctx context.Context) *GetSingleProductParams {
	return &GetSingleProductParams{
		Context: ctx,
	}
}

// NewGetSingleProductParamsWithHTTPClient creates a new GetSingleProductParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSingleProductParamsWithHTTPClient(client *http.Client) *GetSingleProductParams {
	return &GetSingleProductParams{
		HTTPClient: client,
	}
}

/*
GetSingleProductParams contains all the parameters to send to the API endpoint

	for the get single product operation.

	Typically these are written to a http.Request.
*/
type GetSingleProductParams struct {

	/* ID.

	   ID of the product

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get single product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSingleProductParams) WithDefaults() *GetSingleProductParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get single product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSingleProductParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get single product params
func (o *GetSingleProductParams) WithTimeout(timeout time.Duration) *GetSingleProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get single product params
func (o *GetSingleProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get single product params
func (o *GetSingleProductParams) WithContext(ctx context.Context) *GetSingleProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get single product params
func (o *GetSingleProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get single product params
func (o *GetSingleProductParams) WithHTTPClient(client *http.Client) *GetSingleProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get single product params
func (o *GetSingleProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get single product params
func (o *GetSingleProductParams) WithID(id int64) *GetSingleProductParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get single product params
func (o *GetSingleProductParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSingleProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
